version: "2"
run:
  go: "1.24"
  modules-download-mode: mod
linters:
  enable:
    - funlen
    - gosec
    - revive
  disable:
    - dupl
    - godox
  settings:
    funlen:
      lines: 100
      statements: 50
      ignore-comments: true
    gosec:
      excludes:
        - G404
    revive:
      rules:
        - name: unused-parameter
          disabled: true
        - name: dot-imports
          severity: warning
          disabled: false
          exclude:
            - ""
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - .+_test.go
      - .+_gen.go
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
      rewrite-rules:
        - pattern: a[b:len(a)]
          replacement: a[b:]
    goimports:
      local-prefixes:
        - github.com/yvvlee/delay-kafka
  exclusions:
    generated: lax
    paths:
      - .+_test.go
      - .+_gen.go
      - third_party$
      - builtin$
      - examples$
